/** Centralized theme tokens used across screens. */
export const theme = {
  colors: {
    primary: "#0d9488",
    primaryDark: "#0f766e",
    accent: "#14b8a6",
    background: "#f7fbfa",
    card: "#ffffff",
    text: "#1f2937",
    heading: "#134e4a",
    muted: "#5b7772",
    border: "#d8ece7",
    heroFrom: "#d1fae5",
    heroTo: "#99f6e4",
    feature: "#e7f7f2",
    success: "#16a34a",
    danger: "#dc2626",
  },
  fonts: {
    logo: "Comfortaa",
    heading: "Outfit",
    headingExtra: "Outfit",
    body: "Inter",
    bodyMedium: "Inter",
    bodySemiBold: "Inter",
    bodyBold: "Inter",
  },
  radius: 16,
  spacing: (n: number) => n * 8,
};
